"""initial schema

Revision ID: fe09079fac7b
Revises: 
Create Date: 2026-07-21 15:27:40.171090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe09079fac7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('time_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('spice_level', sa.String(length=20), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('salt', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('measurement_type', sa.Enum('WEIGHT', 'VOLUME', 'COUNT', name='measurementtype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nutrients',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('default_unit', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('products',
    sa.Column('ean', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ean')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dish_diets',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'diet_id')
    )
    op.create_table('dish_ingredients',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    op.create_table('dish_regions',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dish_id', 'region_id')
    )
    op.create_table('dish_tools',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dish_id', 'tool_id')
    )
    op.create_table('ingredient_products',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('product_ean', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_ean'], ['products.ean'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ingredient_id', 'product_ean')
    )
    op.create_table('product_allergens',
    sa.Column('product_ean', sa.String(length=20), nullable=False),
    sa.Column('allergen_code', sa.String(length=50), nullable=False),
    sa.Column('contains', sa.Enum('YES', 'NO', 'CAN_CONTAIN_TRACES', name='allergenpresence', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['allergen_code'], ['allergens.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_ean'], ['products.ean'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_ean', 'allergen_code')
    )
    op.create_table('product_nutrition',
    sa.Column('product_ean', sa.String(length=20), nullable=False),
    sa.Column('nutrient_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_code'], ['nutrients.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_ean'], ['products.ean'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_ean', 'nutrient_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_nutrition')
    op.drop_table('product_allergens')
    op.drop_table('ingredient_products')
    op.drop_table('dish_tools')
    op.drop_table('dish_regions')
    op.drop_table('dish_ingredients')
    op.drop_table('dish_diets')
    op.drop_table('tools')
    op.drop_table('regions')
    op.drop_table('products')
    op.drop_table('nutrients')
    op.drop_table('ingredients')
    op.drop_table('dishes')
    op.drop_table('diets')
    op.drop_table('allergens')
    # ### end Alembic commands ###
